name: Deploy Dev

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t ozonemdm-frontend .

      - name: Save Docker Image
        run: |
          docker save ozonemdm-frontend | gzip > frontend.tar.gz

      - name: Copy Image to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_DEV_KEY }}
          port: 22
          source: "frontend.tar.gz"
          target: "/home/ubuntu/"

      - name: Deploy Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_DEV_KEY }}
          port: 22
          script: |
            set -e

            echo "Moving image to docker directory"
            sudo mv /home/ubuntu/frontend.tar.gz /opt/docker/ozonemdm/frontend.tar.gz

            cd /opt/docker/ozonemdm

            echo "Removing old image if exists"
            sudo docker image rm ozonemdm-frontend || true

            echo "Loading new docker image"
            sudo gunzip -c frontend.tar.gz | sudo docker load

            echo "Restarting container"
            sudo docker compose up -d ozonemdm

            echo "Cleaning unused images"
            sudo docker image prune -f
